### ISSUE TITLE
use-sync-external-store/shim/index.js

### ISSUE THREAD

**Issue by Cryptonian87** [thirdweb-example/next-with-typescript#3]
Hello,

I have tried to start the server but couldn't get around the following error :

Error: Cannot find module '../../../node_modules/use-sync-external-store/shim/index.js'
Require stack:
- /node_modules/react-query/build/cjs/packages/react-query/src/useSyncExternalStore.js
- /node_modules/react-query/build/cjs/packages/react-query/src/useQueries.js
- /node_modules/react-query/build/cjs/packages/react-query/src/index.js

Thank you in advance

**Comment by ghost** [comment]
I started using the thirdweb CLI and it worked.

```sh
npx thirdweb create --template next-typescript-starter
```

It seems that the error appears when integrating thirdweb into your existing Next app.

**Comment by jarrodwatts** [comment]
Thanks for raising this @Cryptonian87 and @kjmczk !

This should be fixed in the latest version of the React SDK, we had an issue with our react query dependency.

Let me know if it's working for you now @Cryptonian87 and we can close this one!

**Comment by ghost** [comment]
After upgrading the React SDK to `v2.5.1`, it worked with my existing Next.js app. Thank you @jarrodwatts!
